export const ActionTypes = {

    STORE_EMAIL_VERIFICATION : "STORE_EMAIL_VERIFICATION",
    STORE_EMAIL_OTP : "STORE_EMAIL_OTP",

    // STORE_USER_VERIFICATION : "STORE_USER_VERIFICATION",
    STORE_ADMIN_DETAILS : "STORE_ADMIN_DETAILS",
    STORE_USER_OTP : "STORE_USER_OTP",

    STORE_HOSPITAL_DETAILS : "STORE_HOSPITAL_DETAILS",

    GET_DEPARTMENT_DETAILS : "GET_DEPARTMENT_DETAILS",
    STORE_DEPARTMENT_DETAILS : "STORE_DEPARTMENT_DETAILS",

    GET_WARDS_DETAILS : "GET_WARDS_DETAILS",
    STORE_WARDS_DETAILS :  "STORE_WARDS_DETAILS",
    ADD_WARDS : "ADD_WARDS",

    STORE_BED_DETAILS :  "STORE_BED_DETAILS"

}

