export const ActionTypes = {

    STORE_EMAIL_VERIFICATION : "STORE_EMAIL_VERIFICATION",
    STORE_EMAIL_OTP : "STORE_EMAIL_OTP",
    STORE_USER_VERIFICATION : "STORE_USER_VERIFICATION",
    STORE_USER_OTP : "STORE_USER_OTP",
    STORE_HOSPITAL_DETAILS : "STORE_HOSPITAL_DETAILS",
    STORE_DEPARTMENT_DETAILS : "STORE_DEPARTMENT_DETAILS",
    STORE_WARD_DETAILS :  "STORE_WARD_DETAILS",
    STORE_BED_DETAILS :  "STORE_BED_DETAILS"

}

