export const ActionTypes = {

    STORE_EMAIL_VERIFICATION : "STORE_EMAIL_VERIFICATION",
    STORE_USER_VERIFICATION : "STORE_USER_VERIFICATION",
    STORE_HOSPITAL_DETAILS : "STORE_HOSPITAL_DETAILS",
    STORE_WARD_DETAILS :  "STORE_WARD_DETAILS"
    
}

